# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 455fd4794c846ebce34251ad957a340e008643b030c4aa3cc9b990f6ac93391f988847901cbed9a7743614259f1502e6b25309a7e61fee1ef6df651ca2488fb5

test:
  secret_key_base: 2743ce506b0cf976f92c7a868553df8073f7bd83dde546cf8ce286c4d470a3bf5e6db47e4d25e514aa0193b2b700196cd3b90040ccd0a7843a2d7d6bf366eba5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
